sudo: required

dist: trusty

language: c

os:
  - linux
  - osx

env:
  global:
    - ENCLOSE_IO_MAKE_ARGS="-j4 V="

compiler:
  - gcc
  - clang

script:
  - gem install bundler --no-ri --no-rdoc
  - bundle
  - ENCLOSE_IO_MAKE_ARGS="-j4 V=" bundle exec rake
