language: node_js

node_js: 7.4.0

os:
  - linux
  - osx

env:
  matrix:
    - NODEC_TEST=coffeescript
    - NODEC_TEST=nodeclub

addons:
  apt:
    packages:
      - cmake
      - squashfs-tools

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install squashfs; fi

script:
  - /bin/sh -x tests/test-$NODEC_TEST
