sudo: required

dist: trusty

language: ruby

os:
  - linux
  - osx

env:
  global:
    - ENCLOSE_IO_MAKE_ARGS="-j4 V="

compiler:
  - gcc
  - clang

rvm:
  - 2.3.3

before_install:
  - gem install bundler -v 1.13.6
