language: node_js

node_js: 7.10.0

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - squashfs-tools
      - gcc-4.8
      - g++-4.8

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -rf /usr/local/Cellar/openssl/ && brew install squashfs openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - rvm install ruby-2.4.0
  - rvm use ruby-2.4.0
  - python --version
  - mksquashfs -version
  - ruby --version
  - node --version
  - npm --version

script:
  - ruby tests/coffeescript || exit $?
