gversion: '{build}'

environment:
  GENERATOR: "Visual Studio 14 2015"
  ARCH: 32
  PlatformToolset: v140
  Platform: x86

build_script:
- ps: |
    $ErrorActionPreference="Stop"

    Start-FileDownload https://github.com/pmq20/rubyinstaller/files/689117/rb240-win32.zip -FileName C:\projects\node-compiler\ruby240_win32.zip

    Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName C:\projects\node-compiler\sqfs43-win32.zip

    Start-FileDownload https://github.com/pmq20/node/releases/download/node740-win32/node740-win32.zip -FileName C:\projects\node-compiler\node740-win32.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\ruby240_win32.zip", "C:\projects\node-compiler")

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\sqfs43-win32.zip", "C:\projects\node-compiler\usr\bin")

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\node740-win32.zip", "C:\projects\node-compiler\usr\bin")

test_script:
- cmd: |
    set PATH=C:\projects\node-compiler\usr\bin;%PATH%

    ruby tests/coffeescript

    ruby tests/nodeclub
