version: 1.0.{build}
build_script:
- cmd: >-
    set PATH=C:\Ruby23\bin;%PATH%


    ruby -v

    gem update --system

    gem -v

    gem install bundler

    bundle -v

    bundle install
test_script:
- cmd: >-
    set PATH=C:\Ruby23\bin;%PATH%


    bundle exec rake