version: '{build}'

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      ARCH: 32
      PlatformToolset: v140
      Platform: x86
    - GENERATOR: "Visual Studio 14 2015 Win64"
      ARCH: 64
      PlatformToolset: v140
      Platform: x64

build: off

test_script:
- ps: |
    dir

    Start-FileDownload http://www.enclose.io/rb240-win32.zip -FileName C:\projects\node-compiler\ruby240_win32.zip

    dir

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    dir

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\ruby240_win32.zip", "C:\projects\node-compiler")

    dir

    set PATH=C:\projects\node-compiler\usr\bin;%PATH%

    ruby --version

    cmake --version

    ruby tests/coffeescript

    ruby tests/nodeclub
