version: '{build}'
environment:
  ENCLOSE_IO_VCBUILD_ARGS: nosign
  matrix:
  - ENCLOSE_IO_TEST_NODE_VERSION: node-v6.9.1
  - ENCLOSE_IO_TEST_NODE_VERSION: node-v7.2.0
build_script:
- cmd: >-
    set PATH=C:\Ruby23\bin;%PATH%


    ruby -v

    gem update --system

    gem -v

    gem install bundler

    gem install certified

    echo gem 'certified' >> Gemfile

    certified-update

    bundle -v

    bundle install
test_script:
- cmd: >-
    set PATH=C:\Ruby23\bin;%PATH%


    bundle exec rake
