version: '{build}'

build_script:
- ps: |
    $ErrorActionPreference="Stop"

    Start-FileDownload https://github.com/pmq20/rubyinstaller/files/689117/rb240-win32.zip -FileName C:\projects\node-compiler\ruby240_win32.zip

    Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName C:\projects\node-compiler\sqfs43-win32.zip

    Start-FileDownload https://nodejs.org/dist/v7.7.1/node-v7.7.1-win-x86.zip -FileName C:\projects\node-compiler\node.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\ruby240_win32.zip", "C:\projects\node-compiler")

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\sqfs43-win32.zip", "C:\projects\node-compiler\usr\bin")

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\node.zip", "C:\projects\node-compiler\usr\bin")

test_script:
- cmd: |
    set PATH=C:\projects\node-compiler\usr\bin\node-v7.7.1-win-x86;C:\projects\node-compiler\usr\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64_x86

    python --version

    mksquashfs -version

    ruby --version

    node --version

    npm --version

    ruby tests\coffeescript
