version: 1.0.{build}
build: off
test_script:
- cmd: >-
    echo Compiling a command-line application

    git clone --depth 1 https://github.com/jashkenas/coffeescript.git

    cd coffeescript

    ../bin/nodec bin/coffee


    echo Compiling a web application

    git clone --depth 1 https://github.com/cnodejs/nodeclub.git

    cd nodeclub

    ../bin/nodec app.js