version: '{build}'

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      ARCH: 32
      PlatformToolset: v140
      Platform: x86
    - GENERATOR: "Visual Studio 14 2015 Win64"
      ARCH: 64
      PlatformToolset: v140
      Platform: x64

build_script:
- cmd: |
    cmake --version

    ruby tests/coffeescript

    ruby tests/nodeclub
