version: 1.0.{build}
build_script:
- cmd: >-
    ruby -v

    gem update --system

    gem -v

    gem install bundler

    bundle -v

    bundle install
test_script:
- cmd: bundle exec rake