version: '{build}'

environment:
  GENERATOR: "Visual Studio 14 2015"
  ARCH: 32
  PlatformToolset: v140
  Platform: x86

build_script:
  - ps: |
    $ErrorActionPreference="Stop"

    Start-FileDownload http://www.enclose.io/rb240-win32.zip -FileName C:\projects\node-compiler\ruby240_win32.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\ruby240_win32.zip", "C:\projects\node-compiler")

test_script:
  - cmd: |
    set PATH=C:\projects\node-compiler\usr\bin;%PATH%

    ruby tests/coffeescript

    ruby tests/nodeclub
