version: '{build}'

environment:
  GENERATOR: "Visual Studio 14 2015"
  ARCH: 32
  PlatformToolset: v140
  Platform: x86

build: off

test_script:
- ps: |
    Start-FileDownload http://www.enclose.io/rb240-win32.zip -FileName C:\projects\node-compiler\ruby240_win32.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\node-compiler\ruby240_win32.zip", "C:\projects\node-compiler")

    $env:Path = "C:\projects\node-compiler\usr\bin;" + $env:Path;

    ruby --version

    cmake --version

    ruby tests/coffeescript

    ruby tests/nodeclub
