version: 1.0.{build}
environment:
  ENCLOSE_VCBUILD_ARGS: nosign
  ENCLOSE_IO_TEST_OpenSSL_VERIFY_NONE: 1
  matrix:
  - ENCLOSE_IO_TEST_NODE_VERSION: node-v6.8.0
  - ENCLOSE_IO_TEST_NODE_VERSION: node-v6.9.1
  - ENCLOSE_IO_TEST_NODE_VERSION: node-v7.0.0
build_script:
- cmd: >-
    set PATH=C:\Ruby23\bin;%PATH%


    ruby -v

    gem update --system

    gem -v

    gem install bundler

    bundle -v

    bundle install

    bundle exec certifed-update
test_script:
- cmd: >-
    set PATH=C:\Ruby23\bin;%PATH%


    bundle exec rake